### 회원가입(일반)
POST http://localhost:10000/users/signup
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Password123!",
  "name": "alice"
}

### 로그인
POST http://localhost:10000/users/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Password123!"
}

> {%
    client.global.set("email", response.body.email);
    client.global.set("userRole", response.body.userRole);
    // replace 가 안되서 헤더에서 토큰 정보들을 못가져오고 있다...
%}


### 마이페이지
GET http://localhost:10000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic29jaWFsVHlwZSI6Ik5PTkUiLCJ1c2VySWQiOjEsImp0aSI6ImMzMTJjNmE2LTc5OWUtNDhmNi04OTVlLTAzMjIzNzNiNDU5YyIsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzQ4NTg4NzUyLCJleHAiOjE3NDg1OTIzNTJ9.fsHo858gw30WjinOCBNk87COLk1XWM2xLSuuEqU_07NKZ0LqDeBbZl1ymXbc3O-HbMG0iAaOG9mMO3kCR1G5Fg


### 토큰 재발급
# @no-cookie-jar
POST http://localhost:10000/users/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic29jaWFsVHlwZSI6Ik5PTkUiLCJ1c2VySWQiOjEsImp0aSI6ImMzMTJjNmE2LTc5OWUtNDhmNi04OTVlLTAzMjIzNzNiNDU5YyIsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzQ4NTg4NzUyLCJleHAiOjE3NDg1OTIzNTJ9.fsHo858gw30WjinOCBNk87COLk1XWM2xLSuuEqU_07NKZ0LqDeBbZl1ymXbc3O-HbMG0iAaOG9mMO3kCR1G5Fg
Cookie: RT=f99d96a9-94bb-4154-9934-d6e22ea17e05
