### 회원가입(일반)
POST http://localhost:10000/api/v1/users/signup
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Password123!",
  "name": "alice"
}

### 로그인
POST http://localhost:10000/api/v1/users/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Password123!"
}

> {%
    client.global.set("email", response.body.email);
    client.global.set("userRole", response.body.userRole);
    // replace 가 안되서 헤더에서 토큰 정보들을 못가져오고 있다...
%}


### 마이페이지
GET http://localhost:10000/api/v1/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInNvY2lhbFR5cGUiOiJOT05FIiwidXNlcklkIjoxLCJqdGkiOiIyZTUyNjVlZi01NzQzLTQ0YTctODU4Yy0zMmEwMjM4OGEwZDMiLCJzdWIiOiJ0ZXN0QGdtYWlsLmNvbSIsImlhdCI6MTc0ODgzMzU5NSwiZXhwIjoxNzQ4ODM3MTk1fQ.qGuw3wG9b7U1ZSSLDC_CDBmHNC6taRhwN_YghUFye0MDm-Ba4-u9hGtbo5xwlyEstXfUdjCfnnsp6dBr7rif1A


### 토큰 재발급
# @no-cookie-jar
POST http://localhost:10000/users/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic29jaWFsVHlwZSI6Ik5PTkUiLCJ1c2VySWQiOjEsImp0aSI6Ijg3NDIxMDdkLWI3NzEtNDNmYS05ZjViLWQ0Y2EwY2VjMGU3NSIsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzQ4NjYxOTAyLCJleHAiOjE3NDg2NjU1MDJ9.jH1rYpceigTKbBO9VS29GrAL_HPn-83p4QW_rczcgTTT13KSDvNyXidZZJrayLeZN40sGV_6OE34tKJtB-othQ
Cookie: RT=0d859098-9a1b-4ef5-83f0-5b1d0baf18b6

### 로그아웃
POST http://localhost:10000/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic29jaWFsVHlwZSI6Ik5PTkUiLCJ1c2VySWQiOjEsImp0aSI6IjczZDkxMGZmLWJhMmUtNDk2ZS1hMzcwLWEyZTI3ZDlmZGYzOCIsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzQ4NjYxOTM3LCJleHAiOjE3NDg2NjU1Mzd9.pRyKeEhzgeuvZGxgR4av0IlSwsG4zdCRI3W7fiH13VtOg2R-wspBg9VvI9K7eGpC-JYMRNOmmdCiYSjqoleGNw
Cookie: RT=06233b0f-60a3-47d0-8e81-08f8499e730b


### 회원 동적 조회
GET http://localhost:10000/users?id=1
    &name=홍길동
    &email=test@example.com
    &userRole=ROLE_USER
    &socialType=KAKAO
    &socialId=abc12345
    &createdFrom=2025-01-01T00:00:00
    &createdTo=2025-12-31T23:59:59
    &updatedFrom=2025-01-01T00:00:00
    &updatedTo=2025-12-28T23:59:59
    &deletedFrom=2025-01-01T00:00:00
    &deletedTo=2025-12-31T23:59:59
    &createdBy=10
    &updatedBy=20
    &deletedBy=30
    &page=0
    &size=10
    &sort=createdAt,desc
    &sort=id,desc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic29jaWFsVHlwZSI6Ik5PTkUiLCJ1c2VySWQiOjEsImp0aSI6IjljM2Q2ZjgwLTMxOGItNDEyMy05OTMzLTBhZjhjOGJiNDM0YyIsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzQ4NzQwOTk5LCJleHAiOjE3NDg3NDQ1OTl9.n9uWsSG1rT11rS2SiUXhLUxPS26r8W6E8WivKdZscJtCOwbVbJEX5Aix32IHoZRIbjPpS2TRw_PrdVMReWun5Q

### 회원 동적 조회
GET http://localhost:10000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic29jaWFsVHlwZSI6Ik5PTkUiLCJ1c2VySWQiOjEsImp0aSI6IjNkYzdjZDA1LWU5MTQtNGI4YS1hNTgyLTQ0ZDhiMzNkYmExOCIsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzQ4NzgxMTMyLCJleHAiOjE3NDg3ODQ3MzJ9.NdCwzC0McSZ9ebCR_ir29GnGcemGaKzCgcK6OTwTQbQJuCx7mkHkUiQfjn4mIITRZDjSclCf9BAz7J-E4XcJHQ

### 이메일 인증 코드 전송
POST http://localhost:10000/users/send/email-code
Content-Type: application/json

{
  "email": "optional94@naver.com"
}

### 이메일 코드 인증
POST http://localhost:10000/users/verify/email-code
Content-Type: application/json

{
  "email": "optional94@naver.com",
  "code": "802817"
}


### 비밀번호 수정
PATCH http://localhost:10000/users/password
Content-Type: application/json

{
  "newPassword": "qweqwe123!"
}


### 회원 정보 수정
PATCH http://localhost:10000/users/1/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic29jaWFsVHlwZSI6Ik5PTkUiLCJ1c2VySWQiOjEsImp0aSI6IjdhNjg3ZDY1LWEzMzMtNDFhNi05NWY5LTU5MjYyNjk2MGRmZCIsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzQ4NzYxMjEzLCJleHAiOjE3NDg3NjQ4MTN9.3SGfyrP87c_l24ruUPSD2wcRS1W1Cet66ulMSXXdpkuWyK15ytigrWbzVPVpwZeNMQDgJY6FC0jn4uPLjU-3lg

{
  "newName": "업데이트 이름",
  "newProfileImageUrl": ""
}

### 회원 권한 수정
PATCH http://localhost:10000/users/1/role
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic29jaWFsVHlwZSI6Ik5PTkUiLCJ1c2VySWQiOjEsImp0aSI6IjdhNjg3ZDY1LWEzMzMtNDFhNi05NWY5LTU5MjYyNjk2MGRmZCIsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzQ4NzYxMjEzLCJleHAiOjE3NDg3NjQ4MTN9.3SGfyrP87c_l24ruUPSD2wcRS1W1Cet66ulMSXXdpkuWyK15ytigrWbzVPVpwZeNMQDgJY6FC0jn4uPLjU-3lg

{
  "newUserRole": "ROLE_ADMIN"
}

### 회원 이메일 수정
POST http://localhost:10000/users/1/email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic29jaWFsVHlwZSI6Ik5PTkUiLCJ1c2VySWQiOjEsImp0aSI6IjkyMDU1Y2Q4LWNjOGQtNGUzYy05NmMxLTI0ZDIxMjhiZTlmYSIsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzQ4NzU5NjMyLCJleHAiOjE3NDg3NjMyMzJ9.8D19a_UmfEt4_3sFob1gSHyy8mxd0Isu1JDtO8ZaspGbSoq8wfhhPoVfjrwVyPOpnlXb3o6Zx836gToCUOFAFA

{
  "newEmail": ""
}

### 회원 소프트 삭제
DELETE http://localhost:10000/users/1/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic29jaWFsVHlwZSI6Ik5PTkUiLCJ1c2VySWQiOjEsImp0aSI6IjNkYzdjZDA1LWU5MTQtNGI4YS1hNTgyLTQ0ZDhiMzNkYmExOCIsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzQ4NzgxMTMyLCJleHAiOjE3NDg3ODQ3MzJ9.NdCwzC0McSZ9ebCR_ir29GnGcemGaKzCgcK6OTwTQbQJuCx7mkHkUiQfjn4mIITRZDjSclCf9BAz7J-E4XcJHQ

{}


