### 회원가입(일반)
POST http://localhost:10000/users/signup
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Password123!",
  "name": "alice"
}

### 로그인
POST http://localhost:10000/users/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "Password123!"
}

> {%
    client.global.set("email", response.body.email);
    client.global.set("userRole", response.body.userRole);
    // replace 가 안되서 헤더에서 토큰 정보들을 못가져오고 있다...
%}


### 마이페이지
GET http://localhost:10000/users/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic29jaWFsVHlwZSI6Ik5PTkUiLCJ1c2VySWQiOjEsImp0aSI6Ijg3NDIxMDdkLWI3NzEtNDNmYS05ZjViLWQ0Y2EwY2VjMGU3NSIsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzQ4NjYxOTAyLCJleHAiOjE3NDg2NjU1MDJ9.jH1rYpceigTKbBO9VS29GrAL_HPn-83p4QW_rczcgTTT13KSDvNyXidZZJrayLeZN40sGV_6OE34tKJtB-othQ


### 토큰 재발급
# @no-cookie-jar
POST http://localhost:10000/users/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic29jaWFsVHlwZSI6Ik5PTkUiLCJ1c2VySWQiOjEsImp0aSI6Ijg3NDIxMDdkLWI3NzEtNDNmYS05ZjViLWQ0Y2EwY2VjMGU3NSIsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzQ4NjYxOTAyLCJleHAiOjE3NDg2NjU1MDJ9.jH1rYpceigTKbBO9VS29GrAL_HPn-83p4QW_rczcgTTT13KSDvNyXidZZJrayLeZN40sGV_6OE34tKJtB-othQ
Cookie: RT=0d859098-9a1b-4ef5-83f0-5b1d0baf18b6

### 로그아웃
POST http://localhost:10000/users/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwic29jaWFsVHlwZSI6Ik5PTkUiLCJ1c2VySWQiOjEsImp0aSI6IjczZDkxMGZmLWJhMmUtNDk2ZS1hMzcwLWEyZTI3ZDlmZGYzOCIsInN1YiI6InRlc3RAZ21haWwuY29tIiwiaWF0IjoxNzQ4NjYxOTM3LCJleHAiOjE3NDg2NjU1Mzd9.pRyKeEhzgeuvZGxgR4av0IlSwsG4zdCRI3W7fiH13VtOg2R-wspBg9VvI9K7eGpC-JYMRNOmmdCiYSjqoleGNw
Cookie: RT=06233b0f-60a3-47d0-8e81-08f8499e730b